services:
  - type: web
    name: react-webapp
    env: node
    buildCommand: npm install && npm run build
    startCommand: serve -s build
    envVars:
      - key: NODE_VERSION
        value: 18.0.0 